### ISSUE TITLE
GeoPositioning Interface

### ISSUE THREAD

**Issue by mikebotts** [sensiasoft/sensorhub#12] opened 2015-02-07 00:38 UTC
Create a Java Interface for Position and create instantiations for static location, static position, trajectory, output for a sensor, process-provided, etc. One of these would be used in each appropriate sensor/actuator driver. SensorHub could then take actions such as provide this position in SensorML descriptions, add position to the output offerings, etc.

**Comment by sensiasoft** [comment] 2015-02-14 19:10
Duplicate of [issue #3](../3)

**Closed** 2015-09-06 13:33 UTC
Labels: duplicate, enhancement, sensor-driver
